version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "apitradeable"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zbvoc7j5fftz"
s3_prefix = "apitradeable"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
